openapi: "3.0.0"
info:
  "title": findAllComposers operation
  version:3.0.0
path:
  /findAll
    post:
      tag:
        -composers
      description: Return a list of composers from MongoDB Atlas
      summary: Return a list of documents
      responses:
        '200':
          description: ComposerDocument
        "500" :
          description : Server Document
        "501" : 
          description : MongoDB Exception